services:
  db:
    image: postgis/postgis:16-3.4
    container_name: spot2_db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    command: >
      bash -c "docker-entrypoint.sh postgres &
      sleep 5 &&
      psql -U spot2_user -d spot2_challenge_db -c 'CREATE EXTENSION IF NOT EXISTS postgis;' &&
      wait"

  app:
    build: . 
    container_name: spot2_app
    volumes:
      - .:/app 
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env
    environment:
      DJANGO_SETTINGS_MODULE: spot2.settings

volumes:
  postgres_data: